axis_linear: 5				# RT = right shoulder axis of gamepad
# old/default value of axis_linear: 4	# right directional pad up-down-axis of gamepad
scale_linear: -0.2			# max. linear speed for LB button pressed
scale_linear_turbo: -0.8		# max. linear speed for RB button pressed

axis_angular: 3				# right directional pad left-right-axis of gamepad
scale_angular: 0.5			# max. angular speed

enable_button: 4			# LB = left shoulder button of gamepad
enable_turbo_button: 5			# RB = right shoulder button of gamepad
